#!/usr/bin/env python3
"""
Generate AI Finance Visual for Instagram
Creates professional finance/AI themed images
"""

import matplotlib.pyplot as plt
import matplotlib.patches as patches
import numpy as np
from datetime import datetime
import os

def create_finance_ai_visual(output_path="/tmp/ai_finance_visual.png"):
    """Create a professional AI Finance visual"""
    
    # Set up figure
    plt.figure(figsize=(10, 8), facecolor='#0f172a')
    ax = plt.gca()
    ax.set_facecolor('#0f172a')
    
    # Title
    plt.suptitle('AI + Finance Revolution', 
                fontsize=28, fontweight='bold', color='#60a5fa', y=0.95)
    
    # Subtitle
    plt.title('Claude Code • Trading Algorithms • Financial Automation',
             fontsize=16, color='#94a3b8', pad=20)
    
    # Create 3 main sections
    sections = [
        {
            'title': '🤖 AI Trading',
            'points': [
                '• Algorithmic Strategies',
                '• Real-time Analysis',
                '• Risk Management',
                '• Portfolio Optimization'
            ],
            'color': '#3b82f6',
            'position': (0.15, 0.6)
        },
        {
            'title': '💻 Claude Code',
            'points': [
                '• Financial Scripts',
                '• API Integrations',
                '• Data Pipelines',
                '• Automation Tools'
            ],
            'color': '#10b981',
            'position': (0.5, 0.6)
        },
        {
            'title': '📊 GitHub Repos',
            'points': [
                '• Trading Bots',
                '• Data Analysis',
                '• Risk Models',
                '• Visualization'
            ],
            'color': '#8b5cf6',
            'position': (0.85, 0.6)
        }
    ]
    
    # Draw sections
    for section in sections:
        x, y = section['position']
        
        # Draw circle
        circle = patches.Circle((x, y), 0.08, 
                               facecolor=section['color'] + '20',
                               edgecolor=section['color'],
                               linewidth=2)
        ax.add_patch(circle)
        
        # Section title
        plt.text(x, y + 0.12, section['title'],
                fontsize=14, fontweight='bold',
                color='white', ha='center')
        
        # Points
        for i, point in enumerate(section['points']):
            plt.text(x, y - 0.02 - i*0.05, point,
                    fontsize=10, color='#cbd5e1',
                    ha='center')
    
    # Bottom info
    plt.text(0.5, 0.25, 'Follow for daily AI Finance insights',
            fontsize=12, color='#94a3b8', ha='center')
    
    # Hashtags
    hashtags = '#AIFinance #TradingAlgorithms #ClaudeCode #GitHub #FinancialAI #Automation #FinTech'
    plt.text(0.5, 0.18, hashtags,
            fontsize=11, color='#60a5fa', ha='center')
    
    # Footer
    footer_text = f'Generated by AI • {datetime.now().strftime("%Y-%m-%d")}'
    plt.text(0.5, 0.05, footer_text,
            fontsize=10, color='#64748b', ha='center')
    
    # Remove axes
    ax.set_xticks([])
    ax.set_yticks([])
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.spines['bottom'].set_visible(False)
    ax.spines['left'].set_visible(False)
    
    # Adjust layout
    plt.tight_layout(rect=[0, 0.05, 1, 0.95])
    
    # Save
    plt.savefig(output_path, dpi=300, bbox_inches='tight', facecolor='#0f172a')
    plt.close()
    
    print(f"✅ Created AI Finance visual: {output_path}")
    return output_path

def generate_caption():
    """Generate Instagram caption for finance/AI post"""
    
    caption = """🚀 AI is transforming finance!

From algorithmic trading to automated analysis, AI tools are revolutionizing how we approach financial markets.

🤖 What we're covering:
• AI-powered trading strategies
• Claude Code for financial automation  
• GitHub repos for finance tasks
• Real-time market analysis

💡 Practical applications:
1. Algorithmic trading bots
2. Risk assessment models
3. Portfolio optimization
4. Financial data pipelines

🔧 Tools mentioned:
• Claude Code for scripting
• Python for data analysis
• APIs for real-time data
• GitHub for collaboration

Follow for daily insights into AI + Finance!

#AIFinance #AlgorithmicTrading #ClaudeCode #FinancialAI #TradingBots #GitHub #FinTech #Automation #Python #DataScience #MachineLearning #Investing #Quant #TradingStrategy #FinanceTech"""
    
    return caption

def create_instagram_post_script(image_path, caption):
    """Create script to post to Instagram"""
    
    script = f"""#!/bin/bash
# Instagram Posting Script for AI Finance Content
# Generated: {datetime.now().isoformat()}

echo "📱 Posting AI Finance content to Instagram"
echo "=========================================="

# Check if logged in
echo "🔍 Checking Instagram login status..."
pinchtab text > /tmp/insta_status.json
URL=$(jq -r '.url' /tmp/insta_status.json 2>/dev/null)

if [[ "$URL" != *"instagram.com"* ]] || [[ "$URL" == *"login"* ]]; then
    echo "❌ Not logged into Instagram"
    echo "   Please log in first: pinchtab nav https://www.instagram.com/"
    exit 1
fi

echo "✅ Logged into Instagram"

# Navigate to create page
echo "➕ Going to create post page..."
pinchtab nav "https://www.instagram.com/create/select/"
sleep 3

# Check if we're on create page
pinchtab snap -c > /tmp/create_snapshot.txt
if grep -q "Create" /tmp/create_snapshot.txt; then
    echo "✅ On create post page"
else
    echo "⚠️  Might need manual navigation to create page"
    echo "   Looking for create button..."
    
    # Try to find create button
    pinchtab snap -c | grep -i "create\\|plus\\|add\\|post" | head -5
    echo "   Please click create button manually if needed"
fi

echo ""
echo "📊 POST DETAILS:"
echo "  Image: {image_path}"
echo "  Caption length: {len(caption)} characters"
echo ""
echo "📝 CAPTION PREVIEW:"
echo "{caption[:200]}..."
echo ""
echo "⚠️  IMPORTANT:"
echo "   This script demonstrates the workflow."
echo "   Actual posting requires element mapping for:"
echo "   1. Upload button click"
echo "   2. Image selection"
echo "   3. Caption input"
echo "   4. Share button click"
echo ""
echo "✅ Ready for posting once elements are mapped!"

# Save caption to file for reference
echo "$caption" > /tmp/instagram_caption.txt
echo "📄 Caption saved to: /tmp/instagram_caption.txt"
"""
    
    return script

if __name__ == "__main__":
    print("🎨 Generating AI Finance visual...")
    image_path = create_finance_ai_visual()
    
    print("\n📝 Generating caption...")
    caption = generate_caption()
    
    print("\n📱 Creating Instagram posting script...")
    script_content = create_instagram_post_script(image_path, caption)
    
    # Save script
    script_path = "/tmp/post_ai_finance.sh"
    with open(script_path, "w") as f:
        f.write(script_content)
    
    os.chmod(script_path, 0o755)
    
    print(f"\n✅ COMPLETE!")
    print(f"   Visual: {image_path}")
    print(f"   Script: {script_path}")
    print(f"   Caption: /tmp/instagram_caption.txt")
    
    # Show image info
    import subprocess
    result = subprocess.run(["file", image_path], capture_output=True, text=True)
    print(f"\n📸 Image info: {result.stdout.strip()}")