#!/usr/bin/env python3
"""
Generate AI Finance Visual for Instagram
Simple version without bash script generation
"""

import matplotlib.pyplot as plt
import matplotlib.patches as patches
from datetime import datetime
import os

def create_finance_ai_visual(output_path="/tmp/ai_finance_visual.png"):
    """Create a professional AI Finance visual"""
    
    # Set up figure
    plt.figure(figsize=(10, 8), facecolor='#0f172a')
    ax = plt.gca()
    ax.set_facecolor('#0f172a')
    
    # Title
    plt.suptitle('AI + Finance Revolution', 
                fontsize=28, fontweight='bold', color='#60a5fa', y=0.95)
    
    # Subtitle
    plt.title('Claude Code • Trading Algorithms • Financial Automation',
             fontsize=16, color='#94a3b8', pad=20)
    
    # Create 3 main sections
    sections = [
        {
            'title': '🤖 AI Trading',
            'points': [
                '• Algorithmic Strategies',
                '• Real-time Analysis',
                '• Risk Management',
                '• Portfolio Optimization'
            ],
            'color': '#3b82f6',
            'position': (0.15, 0.6)
        },
        {
            'title': '💻 Claude Code',
            'points': [
                '• Financial Scripts',
                '• API Integrations',
                '• Data Pipelines',
                '• Automation Tools'
            ],
            'color': '#10b981',
            'position': (0.5, 0.6)
        },
        {
            'title': '📊 GitHub Repos',
            'points': [
                '• Trading Bots',
                '• Data Analysis',
                '• Risk Models',
                '• Visualization'
            ],
            'color': '#8b5cf6',
            'position': (0.85, 0.6)
        }
    ]
    
    # Draw sections
    for section in sections:
        x, y = section['position']
        
        # Draw circle
        circle = patches.Circle((x, y), 0.08, 
                               facecolor=section['color'] + '20',
                               edgecolor=section['color'],
                               linewidth=2)
        ax.add_patch(circle)
        
        # Section title
        plt.text(x, y + 0.12, section['title'],
                fontsize=14, fontweight='bold',
                color='white', ha='center')
        
        # Points
        for i, point in enumerate(section['points']):
            plt.text(x, y - 0.02 - i*0.05, point,
                    fontsize=10, color='#cbd5e1',
                    ha='center')
    
    # Bottom info
    plt.text(0.5, 0.25, 'Follow for daily AI Finance insights',
            fontsize=12, color='#94a3b8', ha='center')
    
    # Hashtags
    hashtags = '#AIFinance #TradingAlgorithms #ClaudeCode #GitHub #FinancialAI #Automation #FinTech'
    plt.text(0.5, 0.18, hashtags,
            fontsize=11, color='#60a5fa', ha='center')
    
    # Footer
    footer_text = f'Generated by AI • {datetime.now().strftime("%Y-%m-%d")}'
    plt.text(0.5, 0.05, footer_text,
            fontsize=10, color='#64748b', ha='center')
    
    # Remove axes
    ax.set_xticks([])
    ax.set_yticks([])
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.spines['bottom'].set_visible(False)
    ax.spines['left'].set_visible(False)
    
    # Adjust layout
    plt.tight_layout(rect=[0, 0.05, 1, 0.95])
    
    # Save
    plt.savefig(output_path, dpi=300, bbox_inches='tight', facecolor='#0f172a')
    plt.close()
    
    print(f"✅ Created AI Finance visual: {output_path}")
    return output_path

def generate_caption():
    """Generate Instagram caption for finance/AI post"""
    
    caption = """🚀 AI is transforming finance!

From algorithmic trading to automated analysis, AI tools are revolutionizing how we approach financial markets.

🤖 What we're covering:
• AI-powered trading strategies
• Claude Code for financial automation  
• GitHub repos for finance tasks
• Real-time market analysis

💡 Practical applications:
1. Algorithmic trading bots
2. Risk assessment models
3. Portfolio optimization
4. Financial data pipelines

🔧 Tools mentioned:
• Claude Code for scripting
• Python for data analysis
• APIs for real-time data
• GitHub for collaboration

Follow for daily insights into AI + Finance!

#AIFinance #AlgorithmicTrading #ClaudeCode #FinancialAI #TradingBots #GitHub #FinTech #Automation #Python #DataScience #MachineLearning #Investing #Quant #TradingStrategy #FinanceTech"""
    
    return caption

def create_post_instructions(image_path, caption):
    """Create instructions for posting"""
    
    instructions = f"""📱 INSTAGRAM POSTING INSTRUCTIONS
================================

🎨 GENERATED CONTENT:
• Image: {image_path}
• Caption length: {len(caption)} characters

🚀 POSTING STEPS (Manual):
1. Ensure you're logged into Instagram (servicesell.ai)
2. Click the '+' (Create) button
3. Select the image: {image_path}
4. Add this caption:

{caption}

5. Add relevant hashtags (already in caption)
6. Click 'Share'

🤖 AUTOMATION READY:
• We're logged into Instagram ✅
• PinchTab CLI is working ✅  
• Image is generated ✅
• Caption is ready ✅

⏰ CRON JOB FOR REGULAR POSTING:
Create file: /etc/cron.d/instagram_ai_finance

Add:
# Post AI Finance content daily at optimal times
0 9 * * * root cd /Users/cubiczan/.openclaw/workspace && python3 scripts/create_ai_finance_visual.py
0 12 * * * root /Users/cubiczan/.openclaw/workspace/scripts/post_to_instagram.sh

📊 HASHTAG MONITORING:
# Monitor #AIFinance every 6 hours
0 */6 * * * root /Users/cubiczan/.openclaw/workspace/scripts/instagram_hashtag_monitor.sh AIFinance

✅ READY FOR ACTION!"""
    
    return instructions

if __name__ == "__main__":
    print("🎨 Generating AI Finance visual...")
    image_path = create_finance_ai_visual()
    
    print("\n📝 Generating caption...")
    caption = generate_caption()
    
    print("\n📋 Creating posting instructions...")
    instructions = create_post_instructions(image_path, caption)
    
    # Save files
    caption_file = "/tmp/ai_finance_caption.txt"
    with open(caption_file, "w") as f:
        f.write(caption)
    
    instructions_file = "/tmp/instagram_posting_guide.txt"
    with open(instructions_file, "w") as f:
        f.write(instructions)
    
    print(f"\n✅ COMPLETE!")
    print(f"   Image: {image_path}")
    print(f"   Caption: {caption_file}")
    print(f"   Instructions: {instructions_file}")
    
    # Show image info
    import subprocess
    result = subprocess.run(["file", image_path], capture_output=True, text=True)
    print(f"\n📸 Image info: {result.stdout.strip()}")
    
    print("\n🚀 Ready to post to Instagram!")
    print("   We're currently logged in as: servicesell.ai")