#!/bin/bash
# Monday Gas Price Trades Reminder
# Runs every Monday at 6:00 AM EST

echo "======================================================================"
echo "🎯 MONDAY GAS PRICE TRADES - DEPLOYMENT REMINDER"
echo "======================================================================"
echo ""
echo "📅 Date: $(date)"
echo "⏰ Time: 6:00 AM EST (Monday)"
echo "🎯 Purpose: Review and deploy gas price trades for the week"
echo ""
echo "📊 CURRENT PORTFOLIO STATUS:"
echo "   • Starting Capital: \$413"
echo "   • Active Investments: \$33 (6.3%)"
echo "   • Completed Profits: +\$113"
echo "   • Current Total: \$526"
echo "   • Available for New Trades: \$493"
echo ""
echo "📈 ACTIVE GAS POSITIONS:"
echo "   1. Gas Month (>\$3.50): \$33 total (\$25 + \$8)"
echo "      • Target: >\$3.50 by March 31"
echo "      • Current: Check AAA price"
echo "      • Days Left: Check calendar"
echo ""
echo "🔍 WEEKLY GAS MARKET ANALYSIS NEEDED:"
echo ""
echo "1. 📊 CHECK CURRENT GAS PRICE:"
echo "   • AAA National Average: https://gasprices.aaa.com/"
echo "   • Current price: [CHECK NOW]"
echo "   • Weekly change: [Calculate vs last Monday]"
echo "   • Monthly trend: [Up/Down/Sideways]"
echo ""
echo "2. 📰 REVIEW CATALYSTS:"
echo "   • Iran conflict status (Strait of Hormuz)"
echo "   • OPEC+ production decisions"
echo "   • Refinery maintenance schedules"
echo "   • Seasonal demand (spring driving season)"
echo "   • Economic indicators (driving demand)"
echo ""
echo "3. 🎯 IDENTIFY HIGH-PROBABILITY TRADES:"
echo ""
echo "   A. GAS MONTH TRADES (25+ days):"
echo "      • >\$3.40 (85% probability) - Conservative"
echo "      • >\$3.50 (70% probability) - Current position"
echo "      • >\$3.60 (50% probability) - Aggressive"
echo ""
echo "   B. GAS WEEK TRADES (7 days):"
echo "      • >\$3.25 (90% probability) - Very safe"
echo "      • >\$3.30 (75% probability) - Moderate"
echo "      • >\$3.35 (60% probability) - Aggressive"
echo ""
echo "   C. REGIONAL TRADES:"
echo "      • California >\$4.00 (95% probability)"
echo "      • Midwest >\$3.20 (80% probability)"
echo "      • East Coast >\$3.30 (70% probability)"
echo ""
echo "   D. RANGE TRADES:"
echo "      • \$3.15-\$3.35 (80% probability)"
echo "      • \$3.20-\$3.40 (70% probability)"
echo ""
echo "4. 💰 CAPITAL ALLOCATION STRATEGY:"
echo ""
echo "   OPTION A - CONSERVATIVE (\$493 available):"
echo "      • \$150 - Gas Month (>\$3.40)"
echo "      • \$100 - Gas Week (>\$3.25)"
echo "      • \$100 - California Gas (>\$4.00)"
echo "      • \$143 - Reserve"
echo ""
echo "   OPTION B - MODERATE (\$493 available):"
echo "      • \$200 - Add to Gas Month (>\$3.50)"
echo "      • \$150 - Gas Week (>\$3.30)"
echo "      • \$100 - Range Trade (\$3.15-\$3.35)"
echo "      • \$43 - Reserve"
echo ""
echo "   OPTION C - AGGRESSIVE (\$493 available):"
echo "      • \$300 - Gas Month (>\$3.60)"
echo "      • \$150 - Gas Week (>\$3.35)"
echo "      • \$43 - Reserve"
echo ""
echo "5. ⚠️ RISK MANAGEMENT:"
echo "   • Maximum position size: 5% of portfolio per trade"
echo "   • Maximum gas exposure: 30% of portfolio"
echo "   • Stop-loss consideration: 20% drawdown"
echo "   • Profit target: 50% return or weekly close"
echo ""
echo "6. 📅 WEEKLY SCHEDULE:"
echo "   • Monday 6 AM: This reminder + trade deployment"
echo "   • Wednesday 11 AM: EIA inventory report (major catalyst)"
echo "   • Friday 5 PM: Weekly position review"
echo "   • Daily: Gas price check (9 AM)"
echo ""
echo "7. 🚀 IMMEDIATE ACTIONS:"
echo ""
echo "   STEP 1 - RESEARCH (6:00-6:15 AM):"
echo "     1. Check AAA gas price"
echo "     2. Review weekend news (Iran, OPEC, etc.)"
echo "     3. Check Kalshi market availability"
echo "     4. Review current YES/NO prices"
echo ""
echo "   STEP 2 - ANALYSIS (6:15-6:30 AM):"
echo "     1. Determine probability for each trade type"
echo "     2. Calculate risk/reward ratios"
echo "     3. Select top 2-3 opportunities"
echo "     4. Determine position sizes"
echo ""
echo "   STEP 3 - EXECUTION (6:30-7:00 AM):"
echo "     1. Place orders on Kalshi"
echo "     2. Update portfolio tracker"
echo "     3. Set price alerts"
echo "     4. Document trades"
echo ""
echo "8. 📱 QUICK LINKS:"
echo "   • AAA Gas Prices: https://gasprices.aaa.com/"
echo "   • EIA Weekly Report: https://www.eia.gov/petroleum/supply/weekly/"
echo "   • Kalshi Platform: [Login required]"
echo "   • News: Bloomberg Energy, Reuters Oil, CNBC"
echo ""
echo "9. 📊 SUCCESS METRICS FOR THE WEEK:"
echo "   • Target return: 10-20% on deployed capital"
echo "   • Win rate: >70%"
echo "   • Maximum drawdown: <10%"
echo "   • New insights: 1-2 market patterns discovered"
echo ""
echo "10. 🔄 FOLLOW-UP REMINDERS:"
echo "    • Wednesday 10:45 AM: EIA preparation"
echo "    • Wednesday 11:00 AM: EIA report release"
echo "    • Friday 5:00 PM: Weekly review"
echo "    • Next Monday 6:00 AM: Repeat this process"
echo ""
echo "======================================================================"
echo ""
echo "💡 TIP: Monday morning is optimal for gas trades because:"
echo "       1. Weekend news is priced in"
echo "       2. Full trading week ahead"
echo "       3. EIA report on Wednesday provides mid-week catalyst"
echo "       4. Weekend risk is minimized"
echo ""
echo "🎯 REMEMBER: Gas Week trades settle on Friday,"
echo "             so Monday entries give 5 full trading days."
echo ""
echo "✅ Reminder set: $(date '+%Y-%m-%d %H:%M:%S')"
echo "⏰ Next: Execute trades between 6:00-7:00 AM EST"
echo "📅 Next Monday: Repeat process with updated analysis"