#!/usr/bin/env python3
"""
PDF Report Generator using fpdf2
Creates lead magnet PDFs for outreach campaigns
No system dependencies required (unlike WeasyPrint)
"""

from fpdf import FPDF
from datetime import datetime
import os

class LeadMagnetPDF(FPDF):
    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=15)
    
    def header(self):
        self.set_font('Helvetica', 'B', 16)
        self.cell(0, 10, 'Custom Business Analysis', new_x="LMARGIN", new_y="NEXT", align='C')
        self.ln(5)
    
    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.cell(0, 10, f'Generated by Mac Mini AI Agent | {datetime.now().strftime("%Y-%m-%d")}', align='C')

def create_savings_report(company_name, employee_count, potential_savings, output_path):
    """Create a savings analysis PDF report"""
    pdf = LeadMagnetPDF()
    pdf.add_page()
    
    # Title
    pdf.set_font('Helvetica', 'B', 20)
    pdf.cell(0, 15, f'{company_name}', new_x="LMARGIN", new_y="NEXT", align='C')
    pdf.set_font('Helvetica', '', 14)
    pdf.cell(0, 10, 'Expense Reduction Analysis', new_x="LMARGIN", new_y="NEXT", align='C')
    pdf.ln(10)
    
    # Summary
    pdf.set_font('Helvetica', 'B', 12)
    pdf.cell(0, 10, 'Executive Summary', new_x="LMARGIN", new_y="NEXT")
    pdf.set_font('Helvetica', '', 11)
    
    summary_text = f"""Based on our analysis of companies similar to {company_name} with {employee_count} employees, we've identified significant opportunities for expense reduction across multiple cost categories."""
    
    pdf.multi_cell(0, 7, summary_text)
    pdf.ln(5)
    
    # Savings breakdown
    pdf.set_font('Helvetica', 'B', 12)
    pdf.cell(0, 10, 'Projected Annual Savings', new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font('Helvetica', '', 11)
    savings_items = [
        ('SaaS & Software', f'${potential_savings * 0.3:,.0f}'),
        ('Telecom & Internet', f'${potential_savings * 0.2:,.0f}'),
        ('Vendor Contracts', f'${potential_savings * 0.25:,.0f}'),
        ('Travel & Expense', f'${potential_savings * 0.15:,.0f}'),
        ('Other OPEX', f'${potential_savings * 0.1:,.0f}')
    ]
    
    for item, amount in savings_items:
        pdf.cell(100, 7, f'  - {item}', new_x="RIGHT")
        pdf.cell(0, 7, amount, new_x="LMARGIN", new_y="NEXT")
    
    pdf.ln(5)
    pdf.set_font('Helvetica', 'B', 14)
    pdf.cell(100, 10, 'Total Potential Savings:', new_x="RIGHT")
    pdf.cell(0, 10, f'${potential_savings:,.0f}/year', new_x="LMARGIN", new_y="NEXT")
    
    pdf.ln(10)
    
    # Next steps
    pdf.set_font('Helvetica', 'B', 12)
    pdf.cell(0, 10, 'Recommended Next Steps', new_x="LMARGIN", new_y="NEXT")
    pdf.set_font('Helvetica', '', 11)
    
    steps = [
        '1. Schedule a 15-minute discovery call',
        '2. Share recent expense data for detailed analysis',
        '3. Receive customized savings roadmap',
        '4. Implement with zero upfront cost'
    ]
    
    for step in steps:
        pdf.cell(0, 7, f'  {step}', new_x="LMARGIN", new_y="NEXT")
    
    pdf.ln(10)
    
    # Contact
    pdf.set_font('Helvetica', 'B', 11)
    pdf.cell(0, 7, 'Ready to start saving?', new_x="LMARGIN", new_y="NEXT")
    pdf.set_font('Helvetica', '', 11)
    pdf.cell(0, 7, 'Contact: Zander@agentmail.to', new_x="LMARGIN", new_y="NEXT")
    
    # Save
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    pdf.output(output_path)
    return output_path

def create_wellness_report(company_name, employee_count, savings, output_path):
    """Create a Wellness 125 savings report"""
    pdf = LeadMagnetPDF()
    pdf.add_page()
    
    # Title
    pdf.set_font('Helvetica', 'B', 20)
    pdf.cell(0, 15, f'{company_name}', new_x="LMARGIN", new_y="NEXT", align='C')
    pdf.set_font('Helvetica', '', 14)
    pdf.cell(0, 10, 'Wellness 125 Cafeteria Plan Savings', new_x="LMARGIN", new_y="NEXT", align='C')
    pdf.ln(10)
    
    # Employer savings
    pdf.set_font('Helvetica', 'B', 12)
    pdf.cell(0, 10, 'Employer Savings', new_x="LMARGIN", new_y="NEXT")
    pdf.set_font('Helvetica', '', 11)
    
    pdf.cell(100, 7, f'  FICA Savings:', new_x="RIGHT")
    pdf.cell(0, 7, f'${savings * 0.7:,.0f}/year', new_x="LMARGIN", new_y="NEXT")
    
    pdf.cell(100, 7, f'  Workers Comp Reduction:', new_x="RIGHT")
    pdf.cell(0, 7, f'${savings * 0.3:,.0f}/year', new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font('Helvetica', 'B', 12)
    pdf.cell(100, 10, 'Total Employer Savings:', new_x="RIGHT")
    pdf.cell(0, 10, f'${savings:,.0f}/year', new_x="LMARGIN", new_y="NEXT")
    
    pdf.ln(10)
    
    # Employee benefits
    pdf.set_font('Helvetica', 'B', 12)
    pdf.cell(0, 10, 'Employee Benefits', new_x="LMARGIN", new_y="NEXT")
    pdf.set_font('Helvetica', '', 11)
    
    benefits = [
        'Net pay increase: $50-$400/month',
        '24/7 virtual healthcare (free)',
        'Free generic medications',
        'Dental discounts up to 60%',
        'Wellness programs included'
    ]
    
    for benefit in benefits:
        pdf.cell(0, 7, f'  - {benefit}', new_x="LMARGIN", new_y="NEXT")
    
    pdf.ln(10)
    
    # Contact
    pdf.set_font('Helvetica', 'B', 11)
    pdf.cell(0, 7, 'Zero cost to implement. 30-60 day rollout.', new_x="LMARGIN", new_y="NEXT")
    pdf.set_font('Helvetica', '', 11)
    pdf.cell(0, 7, 'Contact: Zane@agentmail.to', new_x="LMARGIN", new_y="NEXT")
    
    pdf.output(output_path)
    return output_path

if __name__ == "__main__":
    print("\n" + "="*60)
    print("PDF Report Generator (fpdf2)")
    print("="*60 + "\n")
    
    # Test expense reduction report
    output1 = create_savings_report(
        company_name="Test Company Inc",
        employee_count=100,
        potential_savings=150000,
        output_path="/tmp/expense-report.pdf"
    )
    print(f"✅ Expense report: {output1}")
    
    # Test wellness report
    output2 = create_wellness_report(
        company_name="Test Company Inc",
        employee_count=100,
        savings=68100,
        output_path="/tmp/wellness-report.pdf"
    )
    print(f"✅ Wellness report: {output2}")
    
    print("\n✅ PDF generation working!")
    print("="*60 + "\n")
